services:
  api:
    build:
      context: .
      dockerfile: ./src/Dockerfile
      target: development
    command: >
      sh -c "npm run migration:run 
      && npm run start:dev"
    env_file:
      - .env
    depends_on:
      - postgres-db
      - rabbitmq
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - '${PORT}:${PORT}'
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
  postgres-db:
    image: postgres:latest
    hostname: docker-postgres
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'